config/routes.rb
Rails.application.routes.draw do
  root 'pets#index'

  devise_for :users, :path => 'accounts'

  resources :pets do
    resources :needs
  end

  resources :needs do
    resources :treatments
  end

end

app/models/need.rb
class Need < ActiveRecord::Base
  belongs_to :pet
  has_many :treatments, dependent: :destroy
end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
  has_many :needs, dependent: :destroy
  has_many :treatments, through: :needs # pet.treatments
end

app/models/treatment.rb
class Treatment < ActiveRecord::Base
  belongs_to :need
end

app/models/user.rb
class User < ActiveRecord::Base
  # mms: I see (in your other models) that you are utilizing `dependent: :destroy`, should something be destroyed when a user is deleted.
  has_many :pets
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # mms: no authentication?
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  def index
    @pet = Pet.find(params[:pet_id])
    @needs = @pet.need.all
  end

  def new
    @pet = Pet.find(params[:pet_id])
    @need = Need.new
  end

  def create
    @pet = Pet.find(params[:pet_id])
    @need = @pet.needs.create(need_params)

    redirect_to pet_path(@pet)
  end

  def show
    @pet = Pet.find(params[:pet_id])
    @need = Need.find(params[:id])
  end

  def edit
    @pet = Pet.find(params[:pet_id])
    @need = Need.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:pet_id])
    @need = Need.find(params[:id])
    @need.update(need_params)

    redirect_to pet_path( @pet )
  end

  def destroy
    @pet = Pet.find(params[:pet_id])
    @need = Need.find(params[:id])
    @need.destroy

    redirect_to pet_path( @pet )
  end

  private
  def need_params
    params.require(:need).permit(:kind, :symptoms, :created_at, :updated_at, :pet_id, :notes)
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  # before any post action happens, it will authenticate the user
  # mms: only pet's actions?
  before_action :authenticate_user!

  def index
    @pets = current_user.pets
  end

  def show
    @pet = current_user.pets.find(params[:id])
  end

  def new
    @pet = current_user.pets.build
  end

  def edit
    @pet = current_user.pets.find(params[:id])
  end

  def create
    @pet = current_user.pets.new(pet_params)
    if @pet.save
      redirect_to pets_path
    else
      render 'new'
    end
  end

  def update
    @pet = current_user.pets.find(params[:id])
    if @pet.update(pet_params)
      redirect_to pet_path
    else
      render 'edit'
    end
  end

  # mms: destroy?  or delete?
  def destroy
    @pet = current_user.pets.find(params[:id])
    @pet.destroy
    # mms: recommend named routes helper: `root_url`
    redirect_to "/"
  end

  private
  def pet_params
    # mms: we probably do not want to set the created_at, updated_at from the form inputs.
    # mms:   This is about security. We are consciously choosing what attributes can be set via mass-assignment
    params.require(:pet).permit(:user_id, :name, :breed, :pict_url, :vet, :created_at, :updated_at, :weight, :age, :sex, :notes)
  end
end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController
  # def index
  #   @pet = current_user.pet.find(params[:id])
  #   @needs = @pet.need.all
  # end

  def new
    # @pet = Pet.find(params[:need_id])
    @treatment = Treatment.new
  end

  def create
    @need = Need.find(params[:need_id])
    @pet = @need.pet
    @treatment = @need.treatments.create(treatment_params)

    redirect_to pet_path(@pet)
  end

  # def show
  #   @pet = current_user.pet.find(params[:id])
  #   @need = Need.find(params[:id])
  # end

  def edit
    # mms: you probably want limit this to the current need (pet? user?).
    @treatment = Treatment.find(params[:id])
  end

  def update
    @need = Need.find(params[:need_id])
    @pet = @need.pet
    # mms: same here.  `@pet.treatments.find(params[:id])`
    # mms: routes control the interface to your app - not the associations you use within.
    @treatment = Treatment.find(params[:id])
    @treatment.update(treatment_params)
    # mms: what happens when the update fails?
    redirect_to pet_path( @pet )
  end

  def destroy
    @need = Need.find(params[:need_id])
    @pet = @need.pet
    @treatment = Treatment.find(params[:id])
    @treatment.destroy

    redirect_to pet_path( @pet )
  end

  private
  def treatment_params
    # params.require(:need).permit(:pet_id)
    params.require(:treatment).permit(:medicine, :dosage, :every, :created_at, :updated_at, :need_id, :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Special Needs Pets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='//fonts.googleapis.com/css?family=Lato|Source+Sans+Pro|Raleway' rel='stylesheet' type='text/css'>
</head>
<body>
  <div class="container">
    <nav class="nav">
      <ul>
        <li><%= link_to 'Home', pets_path %></li>
        <li><%= link_to("Add New Pet", new_pet_path(@pet), :class => 'action new') %></li>
        <li><%= link_to 'Account', edit_user_registration_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
      </ul>
    </nav>
    <header>
      <!-- mms: The main idea for the page (the H1) probably changes for each page.  On pet#show, it's the Pet. -->
      <h1 class="title">Special Needs Pets</h1>
    </header>
    <%= yield %>
  </div>
</body>
</html>

<!-- add this later: -->
<!-- <%# if current_user %>
  <h3><%#= link_to 'Signout', destroy_user_session_path, :method => :delete %></h3>
<%# else %>
  <h3><%#= link_to 'Signup', new_user_registration_path %></h3>
  <h3><%#= link_to 'Login', new_user_session_path %></h3>
<%# end %> -->

app/views/needs/edit.html.erb
<h2>Edit Need</h2>

<%= form_for [@pet, @need] do |f| %>
  <%= f.label :kind %>
  <%= f.text_field :kind %>

  <%= f.label :symptoms %>
  <%= f.text_field :symptoms %>

  <%= f.label :notes %>
  <%= f.text_area :notes %>

  <%= f.submit %>
<% end %>

<%= form_for [@pet, @need], method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>

app/views/needs/index.html.erb
<h1>Needs#index</h1>
<p>Find me in app/views/needs/index.html.erb</p>

app/views/needs/new.html.erb
<h2>Create Need</h2>

<%= form_for [@pet, @need] do |f| %>
  <%= f.label :kind %>
  <%= f.text_field :kind %>

  <%= f.label :symptoms %>
  <%= f.text_field :symptoms %>

  <%= f.label :notes %>
  <%= f.text_area :notes %>

  <%= f.submit %>
<% end %>

app/views/needs/show.html.erb
<h1>Needs#show</h1>
<p>Find me in app/views/needs/show.html.erb</p>

app/views/pets/_form_new.html.erb
<%= form_for @pet do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :breed %>
  <%= f.text_field :breed %>

  <%= f.label :pict_url %>
  <%= f.text_field :pict_url %>

  <%= f.submit %>
<% end %>

app/views/pets/delete.html.erb
<!-- mms: delete is an action - the result of pressing delete on another view. -->
<!-- mms:   What controller and action is this form submitting to? -->
<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="pets delete">
  <h2>Delete Pet</h2>

  <%= form_for(@pet, method: :delete) do |f| %>

    <p>Are you sure you want to permanently delete this subject?</p>

    <p class="reference-name"><%= @pet.name %></p>

    <div class="form-buttons">
      <%= submit_tag("Delete Subject") %>
    </div>

  <% end %>
</div>

app/views/pets/edit.html.erb
<h2>Edit Pet</h2>

<%= render partial: "form_new" %>

<%= form_for @pet, method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>

app/views/pets/index.html.erb
<div class="pets index">
  <!-- <h2>User: <%#= current_user.email %></h2> -->
  <% @pets.each do |pet| %>
    <div class="pets_list">
      <p><%= link_to image_tag(pet.pict_url), pet_path(pet) %></p>
      <p><h3><%= pet.name %></h3></p>
    </div>
  <% end %>
</div>
  <div class="pets checklist">
    <h2>Daily Checklist:</h2>
    <% @pets.each do |pet| %>
      <div>
        <p><%= pet.name %></p>
        <!-- mms: good use of pet.treatments to bypass the need for listing "needs". -->
        <!-- mms:  Now we need to think about "What, specifically, should happen when a user clicks this?" -->
        <% pet.treatments.each do |treatment| %>
        <ul>
          <li>
            <%= check_box_tag(:treatment) %>
            <!-- mms: three labels for one checkbox?  I recommend a new method on treatment: `treatment.summary`. Then you can tweak it easily. -->
            <%= label_tag(:treatment, treatment.medicine) %>
            <%= label_tag(:treatment, treatment.dosage) %>
            <%= label_tag(:treatment, treatment.every) %>
          </li>
        </ul>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/pets/new.html.erb
<h1>Add Pet</h1>
<%= form_for @pet do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :breed %>
    <%= f.text_field :breed %>
  </p>
  <p>
    <%= f.label :pict_url %>
    <%= f.text_field :pict_url %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/pets/show.html.erb
<div class="pets show">
  <h2><%= @pet.name %></h2>

  <%= link_to("Edit Pet", edit_pet_path(@pet), :class => 'action edit') %>

  <!-- mms: tables are usually only used to manage tabluar (row and column) data. -->
  <table class="detail" summary="Pet detail">
    <tr>
      <td><%= image_tag(@pet.pict_url, width: '200', height: '200') %></td>
      <td>
        <table>
          <tr>
            <td>Breed: <%= @pet.breed %></td>
          </tr>
          <tr>
            <td>Gender: <%= @pet.sex %></td>
          </tr>
          <tr>
            <td>Weight: <%= @pet.weight %> lbs.</td>
          </tr>
          <tr>
            <td>Age: <%= @pet.age %> years</td>
          </tr>
          <tr>
            <td>Notes:</td>
          </tr>
          <tr>
            <td><%= @pet.notes %></td>
          </tr>
        </table>
      </td>
    </tr>
  </table>

  <h2> Special Needs</h2>
  <%= link_to("Create New Need", new_pet_need_path(@pet)) %>
  <ul>
    <% @pet.needs.each do |need| %>
    <!-- mms: thought experiment: should all the treaments be nested in the Need's li? -->
    <li><h3><%= need.kind %></h3></li>
    <%= link_to("Edit Need", edit_pet_need_path(@pet, need)) %>
    <li>
      <h4>Treatments</h4>
      <%= link_to("Create New Treatment", new_need_treatment_path(need)) %>
      <ul>
        <% need.treatments.each do |treatment| %>
        <li>
          <%= treatment.medicine %>
        </li>
        <%= link_to("Edit Treatments", edit_need_treatment_path(need, treatment)) %>
        <% end %>
      </ul>
    </li>
    <% end %>
  </ul>
</div>

app/views/treatments/edit.html.erb
<h2>Edit Treatment</h2>

<%= form_for @treatment, url: {action: "update"} do |f| %>
  <%= f.label :medicine %>
  <%= f.text_field :medicine %>

  <%= f.label :dosage %>
  <%= f.text_field :dosage %>

  <%= f.label :every %>
  <%= f.text_field :every %>

  <%= f.label :notes %>
  <%= f.text_area :notes %>

  <%= f.submit %>
<% end %>

<%= form_for @treatment, url: {action: "destroy"}, method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>

app/views/treatments/index.html.erb
<h1>Treatments#index</h1>
<p>Find me in app/views/treatments/index.html.erb</p>

app/views/treatments/new.html.erb
<h2>Create Treatment</h2>

  <%= form_for @treatment, url: {action: "create"} do |f| %>
  <%= f.label :medicine %>
  <%= f.text_field :medicine %>

  <%= f.label :dosage %>
  <%= f.text_field :dosage %>

  <%= f.label :every %>
  <%= f.text_field :every %>

  <%= f.label :notes %>
  <%= f.text_area :notes %>

  <%= f.submit %>
<% end %>

app/views/treatments/show.html.erb
<h1>Treatments#show</h1>
<p>Find me in app/views/treatments/show.html.erb</p>